EnhancerEP.gems = {
	["Balanced Shadowsong Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32213,
		["ATTACKPOWER"] = 10,
		["STA"] = 7,
		["Red"] = true,
		["Blue"] = true,
	},
	["Bold Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32193,
		["STR"] = 10,
		["Red"] = true,
	},
	["Bright Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32197,
		["ATTACKPOWER"] = 20,
		["Red"] = true,
	},
	["Brilliant Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32204,
		["INT"] = 10,
		["Yellow"] = true,
	},
	["Dazzling Seaspray Emerald"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32225,
		["INT"] = 5,
		["MANAREG"] = 2,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Delicate Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32194,
		["AGI"] = 10,
		["Red"] = true,
	},
	["Enduring Seaspray Emerald"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32223,
		["STA"] = 7,
		["CR_DEFENSE"] = 5,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Flashing Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32199,
		["CR_PARRY"] = 10,
		["Red"] = true,
	},
	["Gleaming Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32207,
		["CR_SPELLCRIT"] = 10,
		["Yellow"] = true,
	},
	["Glinting Pyrestone"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32220,
		["AGI"] = 5,
		["CR_HIT"] = 5,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Glowing Shadowsong Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32215,
		["STA"] = 7,
		["DMG"] = 6,
		["Red"] = true,
		["Blue"] = true,
	},
	["Great Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32210,
		["CR_SPELLHIT"] = 10,
		["Yellow"] = true,
	},
	["Infused Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 31116,
		["STA"] = 6,
		["DMG"] = 6,
		["Red"] = true,
		["Blue"] = true,
	},
	["Infused Shadowsong Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32214,
		["ATTACKPOWER"] = 10,
		["MANAREG"] = 2,
		["Red"] = true,
		["Blue"] = true,
	},
	["Inscribed Pyrestone"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32217,
		["STR"] = 5,
		["CR_CRIT"] = 5,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Jagged Seaspray Emerald"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32226,
		["CR_CRIT"] = 5,
		["STA"] = 7,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Luminous Pyrestone"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32219,
		["INT"] = 5,
		["HEAL"] = 11,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Lustrous Empyrean Sapphire"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32202,
		["MANAREG"] = 4,
		["Blue"] = true,
	},
	["Mystic Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32209,
		["CR_RESILIENCE"] = 10,
		["Yellow"] = true,
	},
	["Potent Pyrestone"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32218,
		["CR_SPELLCRIT"] = 5,
		["DMG"] = 6,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Pulsing Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 31118,
		["ATTACKPOWER"] = 10,
		["STA"] = 6,
		["Red"] = true,
		["Blue"] = true,
	},
	["Radiant Seaspray Emerald"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32224,
		["SPELLPEN"] = 6,
		["CR_SPELLCRIT"] = 5,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Rigid Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32206,
		["CR_HIT"] = 10,
		["Yellow"] = true,
	},
	["Royal Shadowsong Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32216,
		["MANAREG"] = 2,
		["HEAL"] = 11,
		["Red"] = true,
		["Blue"] = true,
	},
	["Runed Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32196,
		["DMG"] = 12,
		["Red"] = true,
	},
	["Shifting Shadowsong Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32212,
		["AGI"] = 5,
		["STA"] = 7,
		["Red"] = true,
		["Blue"] = true,
	},
	["Smooth Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32205,
		["CR_CRIT"] = 10,
		["Yellow"] = true,
	},
	["Solid Empyrean Sapphire"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32200,
		["STA"] = 15,
		["Blue"] = true,
	},
	["Soothing Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 31117,
		["STA"] = 6,
		["HEAL"] = 11,
		["Red"] = true,
		["Blue"] = true,
	},
	["Sovereign Shadowsong Amethyst"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32211,
		["STR"] = 5,
		["STA"] = 7,
		["Red"] = true,
		["Blue"] = true,
	},
	["Sparkling Empyrean Sapphire"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32201,
		["SPI"] = 10,
		["Blue"] = true,
	},
	["Stormy Empyrean Sapphire"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32203,
		["SPELLPEN"] = 13,
		["Blue"] = true,
	},
	["Subtle Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32198,
		["CR_DODGE"] = 10,
		["Red"] = true,
	},
	["Teardrop Crimson Spinel"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32195,
		["HEAL"] = 22,
		["Red"] = true,
	},
	["Thick Lionseye"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32208,
		["CR_DEFENSE"] = 10,
		["Yellow"] = true,
	},
	["Veiled Pyrestone"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32221,
		["CR_SPELLHIT"] = 5,
		["DMG"] = 6,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Void Sphere"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 22459,
		["Red"] = true,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Wicked Pyrestone"] = {
		["Gem Quality"] = 4,
		["ItemID"] = 32222,
		["ATTACKPOWER"] = 10,
		["CR_CRIT"] = 5,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Balanced Nightseye"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 31863,
		["ATTACKPOWER"] = 8,
		["STA"] = 6,
		["Red"] = true,
		["Blue"] = true,
	},
	["Bold Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24027,
		["STR"] = 8,
		["Red"] = true,
	},
	["Bracing Earthstorm Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25897,
		["HEAL"] = 26,
		["Meta Gem"] = true,
	},
	["Bright Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24031,
		["ATTACKPOWER"] = 16,
		["Red"] = true,
	},
	["Brilliant Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24047,
		["INT"] = 8,
		["Yellow"] = true,
	},
	["Brutal Earthstorm Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25899,
		["Meta Gem"] = true,
	},
	["Dazzling Talasite"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24065,
		["INT"] = 4,
		["MANAREG"] = 2,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Delicate Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24028,
		["AGI"] = 8,
		["Red"] = true,
	},
	["Destructive Skyfire Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25890,
		["Meta Gem"] = true,
	},
	["Enduring Talasite"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24062,
		["STA"] = 6,
		["CR_DEFENSE"] = 4,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Enigmatic Skyfire Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25895,
		["CR_CRIT"] = 12,
		["Meta Gem"] = true,
	},
	["Flashing Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24036,
		["CR_PARRY"] = 8,
		["Red"] = true,
	},
	["Gleaming Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24050,
		["CR_SPELLCRIT"] = 8,
		["Yellow"] = true,
	},
	["Glinting Noble Topaz"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24061,
		["AGI"] = 4,
		["CR_HIT"] = 4,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Glowing Nightseye"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24056,
		["STA"] = 6,
		["DMG"] = 5,
		["Red"] = true,
		["Blue"] = true,
	},
	["Great Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 31861,
		["CR_SPELLHIT"] = 8,
		["Yellow"] = true,
	},
	["Imbued Unstable Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 32641,
		["DMG"] = 14,
		["Meta Gem"] = true,
	},
	["Infused Nightseye"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 31865,
		["ATTACKPOWER"] = 8,
		["MANAREG"] = 2,
		["Red"] = true,
		["Blue"] = true,
	},
	["Inscribed Noble Topaz"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24058,
		["STR"] = 4,
		["CR_CRIT"] = 4,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Insightful Earthstorm Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25901,
		["INT"] = 12,
		["Meta Gem"] = true,
	},
	["Jagged Talasite"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24067,
		["CR_CRIT"] = 4,
		["STA"] = 6,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Luminous Noble Topaz"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24060,
		["INT"] = 4,
		["HEAL"] = 9,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Lustrous Star of Elune"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24037,
		["MANAREG"] = 3,
		["Blue"] = true,
	},
	["Mystic Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24053,
		["CR_RESILIENCE"] = 8,
		["Yellow"] = true,
	},
	["Mystical Skyfire Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25893,
		["Meta Gem"] = true,
	},
	["Potent Noble Topaz"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24059,
		["CR_SPELLCRIT"] = 4,
		["DMG"] = 5,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Potent Unstable Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 32640,
		["ATTACKPOWER"] = 24,
		["Meta Gem"] = true,
	},
	["Powerful Earthstorm Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25896,
		["STA"] = 18,
		["Meta Gem"] = true,
	},
	["Prismatic Sphere"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 22460,
		["Red"] = true,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Purified Shadow Pearl"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 32836,
		["SPI"] = 4,
		["HEAL"] = 9,
		["Red"] = true,
		["Blue"] = true,
	},
	["Radiant Talasite"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24066,
		["SPELLPEN"] = 5,
		["CR_SPELLCRIT"] = 4,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Relentless Earthstorm Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 32409,
		["AGI"] = 12,
		["Meta Gem"] = true,
	},
	["Rigid Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24051,
		["CR_HIT"] = 8,
		["Yellow"] = true,
	},
	["Royal Nightseye"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24057,
		["MANAREG"] = 2,
		["HEAL"] = 9,
		["Red"] = true,
		["Blue"] = true,
	},
	["Runed Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24030,
		["DMG"] = 9,
		["Red"] = true,
	},
	["Shifting Nightseye"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24055,
		["AGI"] = 4,
		["STA"] = 6,
		["Red"] = true,
		["Blue"] = true,
	},
	["Smooth Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24048,
		["CR_CRIT"] = 8,
		["Yellow"] = true,
	},
	["Solid Star of Elune"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24033,
		["STA"] = 12,
		["Blue"] = true,
	},
	["Sovereign Nightseye"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24054,
		["STR"] = 4,
		["STA"] = 6,
		["Red"] = true,
		["Blue"] = true,
	},
	["Sparkling Star of Elune"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24035,
		["SPI"] = 8,
		["Blue"] = true,
	},
	["Steady Talasite"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 33782,
		["STA"] = 6,
		["CR_RESILIENCE"] = 4,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Stormy Star of Elune"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24039,
		["SPELLPEN"] = 10,
		["Blue"] = true,
	},
	["Subtle Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24032,
		["CR_DODGE"] = 8,
		["Red"] = true,
	},
	["Swift Skyfire Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25894,
		["ATTACKPOWER"] = 24,
		["Meta Gem"] = true,
	},
	["Teardrop Living Ruby"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24029,
		["HEAL"] = 18,
		["Red"] = true,
	},
	["Tenacious Earthstorm Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 25898,
		["CR_DEFENSE"] = 12,
		["Meta Gem"] = true,
	},
	["Thick Dawnstone"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 24052,
		["CR_DEFENSE"] = 8,
		["Yellow"] = true,
	},
	["Thundering Skyfire Diamond"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 32410,
		["Meta Gem"] = true,
	},
	["Veiled Noble Topaz"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 31867,
		["CR_SPELLHIT"] = 4,
		["DMG"] = 5,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Wicked Noble Topaz"] = {
		["Gem Quality"] = 3,
		["ItemID"] = 31868,
		["ATTACKPOWER"] = 8,
		["CR_CRIT"] = 4,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Balanced Shadow Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 31862,
		["ATTACKPOWER"] = 6,
		["STA"] = 4,
		["Red"] = true,
		["Blue"] = true,
	},
	["Bold Blood Garnet"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23095,
		["STR"] = 6,
		["Red"] = true,
	},
	["Bright Blood Garnet"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 28595,
		["ATTACKPOWER"] = 12,
		["Red"] = true,
	},
	["Brilliant Golden Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23113,
		["INT"] = 6,
		["Yellow"] = true,
	},
	["Dazzling Deep Peridot"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23106,
		["INT"] = 3,
		["MANAREG"] = 1,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Delicate Blood Garnet"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23097,
		["AGI"] = 6,
		["Red"] = true,
	},
	["Enduring Deep Peridot"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23105,
		["STA"] = 4,
		["CR_DEFENSE"] = 3,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Gleaming Golden Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23114,
		["CR_SPELLCRIT"] = 6,
		["Yellow"] = true,
	},
	["Glinting Flame Spessarite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23100,
		["AGI"] = 3,
		["CR_HIT"] = 3,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Glowing Shadow Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23108,
		["STA"] = 4,
		["DMG"] = 4,
		["Red"] = true,
		["Blue"] = true,
	},
	["Great Golden Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 31860,
		["CR_SPELLHIT"] = 6,
		["Yellow"] = true,
	},
	["Infused Shadow Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 31864,
		["ATTACKPOWER"] = 6,
		["MANAREG"] = 1,
		["Red"] = true,
		["Blue"] = true,
	},
	["Inscribed Flame Spessarite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23098,
		["STR"] = 3,
		["CR_CRIT"] = 3,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Jagged Deep Peridot"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23104,
		["CR_CRIT"] = 3,
		["STA"] = 4,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Luminous Flame Spessarite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23099,
		["INT"] = 3,
		["HEAL"] = 7,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Lustrous Azure Moonstone"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23121,
		["MANAREG"] = 2,
		["Blue"] = true,
	},
	["Potent Flame Spessarite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23101,
		["CR_SPELLCRIT"] = 3,
		["DMG"] = 4,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Purified Jaggal Pearl"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 32833,
		["SPI"] = 3,
		["HEAL"] = 7,
		["Red"] = true,
		["Blue"] = true,
	},
	["Radiant Deep Peridot"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23103,
		["SPELLPEN"] = 4,
		["CR_SPELLCRIT"] = 3,
		["Blue"] = true,
		["Yellow"] = true,
	},
	["Rigid Golden Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23116,
		["CR_HIT"] = 6,
		["Yellow"] = true,
	},
	["Royal Shadow Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23109,
		["MANAREG"] = 1,
		["HEAL"] = 7,
		["Red"] = true,
		["Blue"] = true,
	},
	["Runed Blood Garnet"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23096,
		["DMG"] = 7,
		["Red"] = true,
	},
	["Shifting Shadow Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23110,
		["AGI"] = 3,
		["STA"] = 4,
		["Red"] = true,
		["Blue"] = true,
	},
	["Smooth Golden Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 28290,
		["CR_CRIT"] = 6,
		["Yellow"] = true,
	},
	["Solid Azure Moonstone"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23118,
		["STA"] = 9,
		["Blue"] = true,
	},
	["Sovereign Shadow Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23111,
		["STR"] = 3,
		["STA"] = 4,
		["Red"] = true,
		["Blue"] = true,
	},
	["Sparkling Azure Moonstone"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23119,
		["SPI"] = 6,
		["Blue"] = true,
	},
	["Stormy Azure Moonstone"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23120,
		["SPELLPEN"] = 8,
		["Blue"] = true,
	},
	["Teardrop Blood Garnet"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23094,
		["HEAL"] = 13,
		["Red"] = true,
	},
	["Thick Golden Draenite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 23115,
		["CR_DEFENSE"] = 6,
		["Yellow"] = true,
	},
	["Veiled Flame Spessarite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 31866,
		["CR_SPELLHIT"] = 3,
		["DMG"] = 4,
		["Red"] = true,
		["Yellow"] = true,
	},
	["Wicked Flame Spessarite"] = {
		["Gem Quality"] = 2,
		["ItemID"] = 31869,
		["ATTACKPOWER"] = 6,
		["CR_CRIT"] = 3,
		["Red"] = true,
		["Yellow"] = true,
	},
};