local L = AceLibrary("AceLocale-2.2"):new("T_Tracking")

L:RegisterTranslations("enUS", function() return {
	["addonname"] = "Tristan's Tracking Menu |cff7fff7f -Ace2-|r",
	["author"] = "Tristan - Frostmane.eu",
	["translator"] = "Using translation by: Tristan - Frostmane.eu",
	
	["Interface\\Icons\\INV_Misc_Flower_02"] = "Find Herbs",
	["Interface\\Icons\\Spell_Nature_Earthquake"] = "Find Minerals",
	["Interface\\Icons\\Racial_Dwarf_FindTreasure"] = "Find Treasure",
	["Interface\\Icons\\Ability_Tracking"] = "Track Beasts",
	["Interface\\Icons\\Spell_Holy_PrayerOfHealing"] = "Track Humanoids",
	["Interface\\Icons\\Ability_Stealth"] = "Track Hidden",
	["Interface\\Icons\\Spell_Frost_SummonWaterElemental"] = "Track Elementals",
	["Interface\\Icons\\Spell_Shadow_DarkSummoning"] = "Track Undead",
	["Interface\\Icons\\Spell_Shadow_SummonFelHunter"] = "Track Demons",
	["Interface\\Icons\\Ability_Racial_Avatar"] = "Track Giants",
	["Interface\\Icons\\INV_Misc_Head_Dragon_01"] = "Track Dragonkin",
	["Interface\\Icons\\Spell_Holy_SenseUndead"] = "Sense Undead",
	["Interface\\Icons\\Spell_Shadow_Metamorphosis"] = "Sense Demons",
	["Interface\\Icons\\INV_Misc_Head_Undead_01"] = "Detect Undead",
	["Interface\\Icons\\Spell_Shadow_SummonInfernal"] = "Detect Demons",
	["Interface\\Icons\\Spell_Nature_AstralRecal"] = "Detect Gahz'ridian",
	["Interface\\Icons\\INV_Misc_Map_01"] = "--- None ---",
	["No tracking active"] = true,
	
	["canceltracking"] = "Cancel Tracking",
	["canceltrackingdesc"] = "Cancels the active tracking",
	["showonenter"] = "Menu OnMouseOver",
	["showonenterdesc"] = "Show the menu when the mouse hovers over the frame",
	["hidemm"] = "Hide minimap",
	["hidemmdesc"] = "Hides the entire minimap cluster when tracking is not active",
	["blinktext"] = "Blink",
	["blinktextdesc"] = "Blinks the text on the frame when tracking is not active",
	["justification"] = "Justify",
	["justificationdesc"] = "Set justification for the text",


	["Find "] = true,
	["Track "] = true,
	["Sense "] = true,
	["Druid"] = true,
	["Track Humanoids"] = true,
	["Cat"] = true,
	["Cancel Tracking"] = true,
	["Show menu on Hover"] = true,
	["--- None ---"] = true,
	["Tristan's Tracking Menu"] = true,
	["Left click to show Menu"] = true,
	["Rightclick to cancel"] = true,
	["Rightclick to recast "] = true,
	["Cast"] = true,
	
	["AceConsole-Commands"] = {"/ttra", "/t_tracking"}
} end)

L:RegisterTranslations("koKR", function() return {
	["addonname"] = "Tristan의 Tracking Menu |cff7fff7f -Ace2-|r",
	["author"] = "Tristan - Frostmane.eu",
	["translator"] = "한글화 작업 - Damjau",
	
	["Interface\\Icons\\INV_Misc_Flower_02"] = "약초 찾기",
	["Interface\\Icons\\Spell_Nature_Earthquake"] = "광물 찾기",
	["Interface\\Icons\\Racial_Dwarf_FindTreasure"] = "보물 찾기",
	["Interface\\Icons\\Ability_Tracking"] = "야수 추적",
	["Interface\\Icons\\Spell_Holy_PrayerOfHealing"] = "인간형 추적",
	["Interface\\Icons\\Ability_Stealth"] = "은신 추적",
	["Interface\\Icons\\Spell_Frost_SummonWaterElemental"] = "정령 추적",
	["Interface\\Icons\\Spell_Shadow_DarkSummoning"] = "언데드 추적",
	["Interface\\Icons\\Spell_Shadow_SummonFelHunter"] = "악마 추적",
	["Interface\\Icons\\Ability_Racial_Avatar"] = "거인 추적",
	["Interface\\Icons\\INV_Misc_Head_Dragon_01"] = "용족 추적",
	["Interface\\Icons\\Spell_Holy_SenseUndead"] = "언데드 감지",
	["Interface\\Icons\\Spell_Shadow_Metamorphosis"] = "악마 감지",
	["Interface\\Icons\\INV_Misc_Head_Undead_01"] = "언데드 감지",
	["Interface\\Icons\\Spell_Shadow_SummonInfernal"] = "악마 감지",
	["Interface\\Icons\\Spell_Nature_AstralRecal"] = "Detect Gahz'ridian",
	["Interface\\Icons\\INV_Misc_Map_01"] = "--- 없음 ---",
	["No tracking active"] = "추적 비활성화",

	["canceltracking"] = "추적 취소",
	["canceltrackingdesc"] = "활성화된 추적을 취소합니다",
	["showonenter"] = "마우스 오버시 메뉴 표시",
	["showonenterdesc"] = "마우스를 프레임 위에 올려 놓을 경우 메뉴를 표시합니다",
	["hidemm"] = "미니맵 숨김",
	["hidemmdesc"] = "추적이 비활성화 되어 있을 때에는 미니맵 전체를 숨깁니다",
	["blinktext"] = "깜빡임",
	["blinktextdesc"] = "추적이 비활성화 되어 있을 때에는 프레임을 깜빡입니다",
	["justification"] = "정렬",
	["justificationdesc"] = "텍스트 정렬 방식을 설정합니다",

	["Find "] = " 찾기",
	["Track "] = " 추적",
	["Sense "] = "^([악마|언데드]+) 감지",
	["Druid"] = "드루이드",
	["Track Humanoids"] = "인간형 추적",
	["Cat"] = "표범",
	["Cancel Tracking"] = "추적 취소",
	["Show menu on Hover"] = "마우스오버시 메뉴 표시",
	["--- None ---"] = "--- 없음 ---",
	["Tristan's Tracking Menu"] = "Tristan의 추적 메뉴",
	["Left click to show Menu"] = "좌클릭시 메뉴 표시",
	["Rightclick to cancel"] = "우클릭시 추적 취소",
	["Rightclick to recast "] = "우클릭시 추적 재시전",
	["Cast"] = "재시전",

} end)
