local L = AceLibrary("AceLocale-2.2"):new("RaidSpy")

L:RegisterTranslations("enUS", function() return {
	["AuthorPrefixed"] = "Author: {$}",
	["VersionPrefixed"] = "Version: {$}",
	["LastUpdatePrefixed"] = "Last Update: {$}",
	["fancyname"] = "{Author} {Title} {Ace}",
	
	["addonname"] = "RaidSpy |cff7fff7f -Ace2-|r",
	["addonnameFu"] = "RaidSpy",
	["author"] = "Tristan - Frostmane.eu",
	["translator"] = "Using translation by: Tristan - Frostmane.eu",
	["Version: $"] = "Version: ",
	["consolecommands"] = {"/ras", "/RaidSpy"},
	
	["AddOnErrorMessagePrefix"] = "|cffffff7fRaidSpy:|r ",
	["ResistanceText"] = "is doing a Resistance Check",
	["ReagentsText"] = "is doing a Reagents Check",
	["DurabilityText"] = "is doing a Durability Check",
	["ItemText"] = "is doing an Item Check for {i}",
	
	["tabletHint"] = "Rightclick for options",
	
	["item_cmd"] = "Item",
	["item_name"] = "Item Checks",
	["item_desc"] = "Alerts you on Item Checks",
	["item_order"] = 5,
	["dura_cmd"] = "Durability",
	["dura_name"] = "Durability Checks",
	["dura_desc"] = "Alerts you on Durability Checks",
	["dura_order"] = 5,
	["reag_cmd"] = "Reagent",
	["reag_name"] = "Reagent Checks",
	["reag_desc"] = "Alerts you on Reagent Checks",
	["reag_order"] = 5,
	["resi_cmd"] = "Resistance",
	["resi_name"] = "Resistance Checks",
	["resi_desc"] = "Alerts you on Resistance Checks",
	["resi_order"] = 5,
	["chatR_cmd"] = "ChatAlert",
	["chatR_name"] = "Chat Alerts",
	["chatR_desc"] = "Activates sending alerts to Chatframe",
	["chatR_order"] = 7,
	["erroR_cmd"] = "ErrorFrameAlert",
	["erroR_name"] = "Error Frame Alerts",
	["erroR_desc"] = "Activates sending alerts to UIErrorFrame",
	["erroR_order"] = 7,
	
	["duraSpy_cmd"] = "DurabilitySpy",
	["duraSpy_name"] = "Durability Spy",
	["duraSpy_desc"] = "Saves durability responses (even from other's /radur) for easy lookup later",
	["duraSpy_order"] = 9,
	["itemSpy_cmd"] = "ItemSpy",
	["itemSpy_name"] = "Item Spy",
	["itemSpy_desc"] = "Saves Item responses (even from other's /raitem) for easy lookup later",
	["itemSpy_order"] = 9,
	
	["cantdoitemcheck"] = "oRA2/CTRA not loaded, only supporting oRA2/CTRA. CTRA untested as of yet.",
	["UnitNotInRaid"] = "You are not part of a raid and can not check for items, duh!",
	
	["predefinedChecks_name"] = "Predefined Checks",
	["predefinedChecks_desc"] = "Certain predefined checks",
	["predefinedChecks_std_name"] = "Standard",
	["predefinedChecks_std_desc"] = "Standard checks",
	["predefinedChecks_zg_name"] = "Zul'Gurub",
	["predefinedChecks_zg_desc"] = "Checks for Zul'Gurub",
	["predefinedChecks_mc_name"] = "Molten Core",
	["predefinedChecks_mc_desc"] = "Checks for Molten Core",
	["predefinedChecks_bwl_name"] = "Blackwing Lair",
	["predefinedChecks_bwl_desc"] = "Checks for Blackwing Lair",
	["predefinedChecks_aq_name"] = "Ahn'Qiraj",
	["predefinedChecks_aq_desc"] = "Checks for Ahn'Qiraj",
	["predefinedChecks_naxx_name"] = "Naxxramas",
	["predefinedChecks_naxx_desc"] = "Checks for Naxxramas",
	["predefinedChecks_kara_name"] = "Karazhan",
	["predefinedChecks_kara_desc"] = "Checks for Karazhan",
	
	["Hearthstone_name"] = "Hearthstone",
	["Hearthstone_desc"] = "Checking for Hearthstone often let's you know if users turned of ItemChecks",
	["Run a check for: "] = true,
	["predefinedCheckItems"] = {
		["std"] = {
			"Field Repair Bot 74A",
			"Remote Mail Terminal",
		},
		["zg"] = {
			"4|Gurubashi Mojo Madness",
			"4|Massive Mojo",
			"4|Powerful Mojo",
			"3|Bloodvine",
			"4|Primal Tiger Leather",
			"4|Primal Bat Leather",
			"2|Zulian Coin",
			"2|Witherbark Coin",
			"2|Vilebranch Coin",
			"2|Skullsplitter Coin",
			"2|Sandfury Coin",
			"2|Razzashi Coin",
			"2|Hakkari Coin",
			"2|Gurubashi Coin",
			"2|Bloodscalp Coin",
			"Yellow Hakkari Bijou",
			"Silver Hakkari Bijou",
			"Red Hakkari Bijou",
			"Purple Hakkari Bijou",
			"Orange Hakkari Bijou",
			"Green Hakkari Bijou",
			"Gold Hakkari Bijou",
			"Bronze Hakkari Bijou",
			"Blue Hakkari Bijou",
		},
		["mc"] = {
			"Aqual Quintessence",
			"Eternal Quintessence",
			"Fiery Core",
			"Lava Core",
		},
		["bwl"] = {
			"Hourglass Sand",
			"Elementium Ore",
		},
		["aq"] = {
			"Greater Scarab Coffer Key",
			"Scarab Coffer Key",
			"5|Heavy Silithid Carapace",
			"5|Light Silithid Carapace",
			"5|Silithid Chitin",
			"5|Large Obsidian Shard",
			"5|Small Obsidian Shard",
			"4|Stone Scarab",
			"4|Silver Scarab",
			"4|Ivory Scarab",
			"4|Gold Scarab",
			"4|Crystal Scarab",
			"4|Clay Scarab",
			"4|Bronze Scarab",
			"4|Bone Scarab",
			"4|Scarab Bag",
			"3|Vermillion Idol",
			"3|Onyx Idol",
			"3|Obsidian Idol",
			"3|Lambent Idol",
			"3|Jasper Idol",
			"2|Idol of the Sun",
			"2|Idol of the Sage",
			"2|Idol of War",
			"2|Idol of Strife",
			"2|Idol of Rebirth",
			"2|Idol of Night",
			"2|Idol of Life",
			"2|Idol of Death",
			"3|Azure Idol",
			"3|Amber Idol",
			"3|Alabaster Idol",
		},
		["naxx"] = {
			"2|Word of Thawing",
			"3|Wartorn Chain Scrap",
			"3|Wartorn Cloth Scrap",
			"3|Wartorn Leather Scrap",
			"3|Wartorn Plate Scrap",
			"Frozen Rune",
		},
		["kara"] = {
			"Soul Essence",
		},
	}
	
} end)
