local L = AceLibrary("AceLocale-2.2"):new("Tankalyze")

L:RegisterTranslations("enUS", function() return {
	["addonname"] = "Tankalyze |cff7fff7f -Ace2-|r",
	["author"] = "Tristan - Frostmane.eu",
	["translator"] = "Using translation by: Tristan - Frostmane.eu",
	["consolecommands"] = {"/Tankalyze", "/ttank", "/ttaunt"},
	
	["ResistTauntRX"] = "Your Taunt was resisted by (%w+)",
	["ResistGrowlRX"] = "Your Growl was resisted by (%w+)",
	["MockingBlowRX"] = "(.*)Mocking Blow(.*)",
	["MockingBlowSuccessRX"] = "Your Mocking Blow (.+) for (.+)",
	["ResistChallengingShoutRX"] = "Your Challenging Shout was resisted by (.*)\.",
	["ResistChallengingRoarRX"] = "Your Challenging Roar was resisted by (.*)\.",
	["ChallengingShoutRX"] = "(.*)Challenging Shout(.*)",
	["ChallengingRoarRX"] = "(.*)Challenging Roar(.*)",
	
	["TauntMessage"] = ">>> Taunt failed against: {t} ({l}) <<<",
	["TauntMessageSCT"] = "Taunt failed: {t}",
	["GrowlMessage"] = ">>> Growl failed against: {t} ({l}) <<<",
	["GrowlMessageSCT"] = "Growl failed: {t}",
	["MockingMessage"] = ">>> Mocking Blow missed against: {t} ({l}) <<<",
	["MockingMessageSCT"] = "Mocking Blow missed: {t}",
	["ShoutMessage"] = ">>> Challenging Shout failed against: {t} ({l}) <<<",
	["ShoutMessageSCT"] = "Challenging Shout failed: {t}",
	["RoarMessage"] = ">>> Challenging Roar failed against: {t} ({l}) <<<",
	["RoarMessageSCT"] = "Challenging Roar failed: {t}",
	["level "] = true,
	["MessagesInfo"] = "Type the text you want to use for the setting {t} will be swapped for targetname and {l} for level (case sensitive)",
	["MessagesInfoNoTarget"] = "Type the text you want to use for the setting",
	["WallUsedMessage"] = ">>> Shield Walling <<<",
	["StandUsedMessage"] = ">>> Last Stand used <<<",
	["GemUsedMessage"] = ">>> Lifegiving Gem used <<<",
	["ShoutUsedMessage"] = ">>> Challenging Shout used (6 sec) <<<",
	["RoarUsedMessage"] = ">>> Challenging Roar used (6 sec) <<<",
	
	["Menu"] = true,
	["Show Menu"] = true,
	["Resists"] = true,
	["Settings for resists"] = true,
	["Resists Messages"] = true,
	["Message settings for resists"] = true,
	["Announces resisted taunts"] = true,
	["Announces resisted growls"] = true,
	["Announces missed Mocking Blows"] = true,
	["Announces resisted challenging shouts"] = true,
	["Announces resisted challenging roars"] = true,
	["Announce To"] = true,
	["Set where to announce"] = true,
	["Custom Chan"] = true,
	["Name of the channel to send to (only used if Announce To is set to CHANNEL)"] = true,
	["Alert Self"] = true,
	["Toggles alert in the standard UI Error Frame"] = true,
	["Don't send in BG's"] = true,
	["Toggles wheter to send messages inside battlegrounds or not"] = true,
	["Scrolling Combat Text Alert"] = true,
	["Toggles message sent to Scrolling Combat Text (if installed) as Combat Flag"] = true,
	["Announces"] = true,
	["Settings for announces"] = true,
	["Announce Messages"] = true,
	["Message settings for announces"] = true,
	["Test"] = true,
	["Send test messages with current settings"] = true,
	["Humour"] = true,
	["Do you have it?"] = true,
	["Logging"] = true,
	["Logging for Challenging Shout/Roar if you want to help"] = "I now have the logs I wanted so no need to keep using this. I keep the setting simply for my own use in case I need it again!",
	
	["Used"] = " used",
	["<No Target>"] = true,
	["<Friendly Target>"] = true,
	["Unknown"] = true,
	["go me"] = true,
	["GG, I just put rend on a worldboss!"] = true,
	["Custom channel not found"] = "Custom channel [|cffff7f7f{c}|r] not found, please type |cff7fff7f/join {c}|r in chat",
	["Hotbar spell found"] = "Spell '|cff77ff77{s}|r' located on hotbars",
	["Hotbar spell not found error"] = "|cffff7777WARNING|r: Couldn't find spell with name '|cffff7777{s}|r' on the hotbars! Some functionallity may be lost",
	["Hotbar spell removed"] = "|cffff7777WARNING|r: spell with name '|cffff7777{s}|r' appear to have been removed from the hotbars! Some functionallity may be lost",
	["Not implemented"] = "Not implemented, not sure it will ever be!",
	
	["ClassificationBoss"] = "worldboss",
	["ClassificationElite"] = "elite",
	
	["|cffffff7fDebug : |r"] = true,
	
	--[[ Spells we cast ]]
	["Lifegiving Gem Menu"] = "Gift of Life (Lifegiving Gem)",
	["Lifegiving Gem"] = "Gift of Life",
		-- * WARRIOR *
			["Sunder Armor"] = true,
			["Revenge"] = true,
			["Heroic Strike"] = true,
			["Shield Bash"] = true,
			["Mocking Blow"] = true,
			["Shield Block"] = true,
			["Shield Slam"] = true,
			["Mortal Strike"] = true,
			["Bloodthirst"] = true,
			["Taunt"] = true,
			["Mocking Blow"] = true,
			["Challenging Shout"] = true,
			["Shield Wall"] = true,
			["Last Stand"] = true,
			["Rend"] = true,
			["Death Wish"] = true,
			["Concussion Blow"] = true,
			["Whirlwind"] = true,
			["Berserker Rage"] = true,
			["Overpower"] = true,
			["Execute"] = true,
			["Intercept"] = true,
			["Improved Heroic Strike"] = true,
			["Improved Sunder Armor"] = true,
		-- * DRUID *
			["Growl"] = true,
			["Challenging Roar"] = true,
} end)
