local L = AceLibrary("AceLocale-2.2"):new("RaidAgent")

L:RegisterTranslations("enUS", function() return {
	["AuthorPrefixed"] = "Author: {$}",
	["VersionPrefixed"] = "Version: {$}",
	["LastUpdatePrefixed"] = "Last Update: {$}",
	["fancyname"] = "{Author} {Title} {Ace}",
	["translator"] = "Tristan-Frostmane[EU]",
	["load_message"] = "{FancyName} v{Version} loaded (using translation by: {Translator})",
	["consolecommands"] = {"/RaidAgent", "/rag"},
	["fubarTabletHint"] = "When in a party then click to convert to raid\nHint: When in raid click to do a ready check\nHint: You can shift-click to leave a group (also works when bugged)\nHint: Right-click for more options",
	
	["RaidStrength_name"] = "RaidStrength",
	["RaidStrength_desc"] = "Calculate RaidStrength",
	["RaidNumbersFu_name"] = "Breakdown raid numbers",
	["RaidNumbersFu_desc"] = "Shows (online/offline/dead/zoned) in FuBar next to raidtotal",
	["special_name"] = "Menu for Special",
	["special_desc"] = "Choose what to display in the tooltip under Special",
	["autoML_name"] = "Auto ML certain Items",
	["autoML_desc"] = "Automatically assigns scraps (Naxx), coins/bijous (ZG) & scarabs/idols (AQ) to a preset person",
	["autoMLItems_name"] = "Set Auto ML items",
	["autoMLItems_desc"] = "Set what items to auto loot in ML mode",
	["randomML_name"] = "Random ML certain Items",
	["randomML_desc"] = "Automatically Randoms out items instead of auto (If you have an auto ML name that takes presedence)",
	["NoAnnounce_name"] = "No group announcements",
	["NoAnnounce_desc"] = "Just hands out items without announcing to the group",
	["BoE_name"] = "BoE's",
	["BoE_desc"] = "Autoloots all BoE's to person specified (or random)",
	["MC_name"] = "Molten Core",
	["MC_desc"] = "Autoloots all Molten Core items to person specified (or random)",
	["BWL_name"] = "Blackwing Lair",
	["BWL_desc"] = "Autoloots all Blackwing Lair items to person specified (or random)",
	["ZG_name"] = "Zul'Gurub",
	["ZG_desc"] = "Autoloots all Zul'Gurub items to person specified (or random)",
	["AQ_name"] = "Ahn'Qiraj",
	["AQ_desc"] = "Autoloots all Ahn'Qiraj items to person specified (or random)",
	["Naxx_name"] = "Naxxramas",
	["Naxx_desc"] = "Autoloots all Naxxramas items to person specified (or random)",
	["sync_name"] = "Send Sync",
	["sync_desc"] = "Manually send a sync message",
	["updateSync_name"] = "Update sync message",
	["updateSync_desc"] = "Updates your sync message and sends a sync",
	["askForSync_name"] = "Beg group to update",
	["askForSync_desc"] = "Ask the entire group to send their sync message",
	["lookup_name"] = "Lookup name",
	["lookup_desc"] = "Manually lookup if you have data for a playername from previous groups",
	
	["FuHintClickRaid"] = "Click to Convert to raid",
	["FuHintClickReady"] = "Click to do ready check",
	["FuHintClickUngroup"] = "Shift click to leave group (works on bugged group too)",
	["FuHintClickReport"] = "Click to report in raid, Shift-Click to report in Officer",
	["FuHintClickName1"] = "Click to toggle (A), Shift-Click to give away (L), Ctrl-Click to give ML, Alt-Click to uninvite",
	["FuHintClickName2"] = "Shift-Ctrl-Click to print Census report, Shift-Ctrl-Alt-Click to send Census report to Raid",
	
	["TabletCatType"] = "Type",
	["TabletCatAmount"] = "Amount",
	["TabletCatName"] = "Name",
	["TabletCatGroup"] = "Group",
	["TabletCatLevel"] = "Level",
	["TabletCatClass"] = "Class",
	["TabletCatSpecial"] = "Special",
	["TabletCatZone"] = "Zone",
	
	["RaidPromoted"] = "(A)",
	["RaidLeader"] = "(L)",
	["RaidML"] = "(ML)",

	["RaidStrengthValues"] = "Raid Strength: {$} (values based on: http://www.wowwiki.com/Class)",
	["RaidStrengthsValues"] = "Raid Strengths: {$} (values based on: http://www.wowwiki.com/Class)",
	["RaidStrengthDPS"] = "DPS",
	["RaidStrengthAoE"] = "AoE",
	["RaidStrengthHeal"] = "Heal",
	["RaidStrengthTank"] = "Tank",
	["RaidStrengthCCPullMA"] = "CC / Pull / MA",
	["RaidStrengthBuffDebuff"] = "Buff / Debuff",
	["Tank"] = true,
	["CC"] = true,
	["Buff"] = true,
	["Heal"] = true,
	["DPS"] = true,
	["Pull"] = true,
	["Debuff"] = true,
	["MA"] = true,
	["AoE"] = true,
	
	["TypeHealers"] = "Healer(s)",
	["TypeTanks"] = "Tank(s)",
	["TypeDPSers"] = "DPSer(s)",
	
	["RaidReportTypes"] = "Currently {Num} {Type} in raid",
	
	["LoggedIntoRaid"] = "Logged into a raid with rank: {$}",
	["NewRaidRank"] = "New rank in raid: {$}",
	
	["Nothing to display"] = true,
	["Not grouped"] = "You are not in a group",
	["Not Synced"] = true,
	["LearnedTalent(s)"] = "Learned new talent(s): {$}",
	["NoTranslationTalent"] = "No translation for talent with ID: {$} (Are you running latest version)",
	["CensusReport"] = "Census report on: {$}",
	["CensusReportNotSynced"] = "* Not synced",
	["CensusReportClass"] = "* Class: {$}",
	["CensusReportYes"] = "Yes",
	["CensusReportNo"] = "No",
	["AutoLoot"] = "Auto giving {Link} to {PlayerName}",
	["RandomLoot"] = "Random giving {Link} to {PlayerName} (rolled {Num})",
	
	["Error_OnlyLeaderCanConvert"] = "Only leader can convert to raid",
	["Error_OnlyLeaderCanReady"] = "Only leader can do ready checks",
	
	--[[ *** Regex *** ]]
	["LootLinkBreakDown"] = "^%|c%x%x(%x+)%|Hitem:(%d+):(%d+):(%d+):(%d+):(%d+):(%d+):(%d+):(%d+)%|h%[(.+)%]%|h%|r$",
	["Binds when equipped"] = true,
	
	--[[ *** CLASSES *** ]]
	["DRUID"] = "Druid",
	["HUNTER"] = "Hunter",
	["MAGE"] = "Mage",
	["PALADIN"] = "Paladin",
	["PRIEST"] = "Priest",
	["ROGUE"] = "Rogue",
	["SHAMAN"] = "Shaman",
	["WARLOCK"] = "Warlock",
	["WARRIOR"] = "Warrior",
	
	--[[ *** TALENTS *** ]]
	["DD_InS"] = "Insect Swarm",
	["DD_MoF"] = "Moonkin Form",
	["DD_IFF"] = "Improved Faire Fire",
	["DD_FFi"] = "Fearie Fire (Feral)",
	["DD_LoP"] = "Leader of the Pack",
	["DD_ILP"] = "Improved Leader of the Pack",
	["DD_Man"] = "Mangle",
	["DD_IMW"] = "Improved Mark of the Wild",
	["DD_NaS"] = "Nature's Swiftness",
	["DD_ToL"] = "Tree of Life",
	
	["HR_Pat"] = "Pathfinding",
	["HR_FeI"] = "Ferocious Inspiration",
	["HR_IHM"] = "Improved Hunter's Mark",
	["HR_TsA"] = "Trueshot Aura",
	["HR_WyS"] = "Wyvern Sting",
	
	["ME_MaA"] = "Magic Attunement",
	["ME_Slo"] = "Slow",
	["ME_ImS"] = "Improved Scorch",
	["ME_WiC"] = "Winter's Chill",
	
	["PN_AMa"] = "Aura Mastery",
	["PN_ILH"] = "Improved Lay on Hand",
	["PN_IBW"] = "Improving Blessing of Wisdom",
	["PN_IDA"] = "Improved Devotion Aura",
	["PN_BoK"] = "Blessing of Kings",
	["PN_ICA"] = "Improved Concentration Aura",
	["PN_IRA"] = "Improved Resistances Aura",
	["PN_BoS"] = "Blessing of Sanctuary",
	["PN_IBM"] = "Improved Blessing of Might",
	["PN_SaA"] = "Sanctity Aura",
	["PN_ISA"] = "Improved Sanctity Aura",
		
	["PT_PWF"] = "Improved Power Word: Fortitude",
	["PT_PWS"] = "Improved Power Word: Shield",
	["PT_DiS"] = "Divine Spirit",
	["PT_IDS"] = "Improved Divine Spirit",
	["PT_PoI"] = "Power Infusion",
	["PT_ReS"] = "Reflective Shield",
	["PT_Ins"] = "Inspiration",
	["PT_HoR"] = "Holy Reach",
	["PT_LiW"] = "Lightwell",
	["PT_ShW"] = "Shadow Weaving",
	["PT_Sil"] = "Silence",
	["PT_VaE"] = "Vampiric Embrace",
	["PT_ShF"] = "Shadow Form",
	["PT_Mis"] = "Misery",
	["PT_VaT"] = "Vampiric Touch",
	
	["RE_ISa"] = "Improved Sap",
	["RE_Hem"] = "Hemorrhage",
	
	["SN_EaG"] = "Earth's Grasp",
	["SN_ElF"] = "Elemental Fury",
	["SN_ToW"] = "Totem of Wrath",
	["SN_GuT"] = "Guardian Totems",
	["SN_IHW"] = "Improved Healing Wave",
	["SN_IRe"] = "Improved Reincarnation",
	["SN_AnH"] = "Ancestral Healing",
	["SN_HeF"] = "Healing Focus",
	["SN_HeG"] = "Healing Grace",
	["SN_ReT"] = "Restorative Totems",
	["SN_HeW"] = "Healing Way",
	["SN_NaS"] = "Nature's Swiftness",
	["SN_FoM"] = "Focused Mind",
	["SN_MTT"] = "Mana Tide Totem",
	["SN_NaG"] = "Nature's Guardian",
	["SN_NaB"] = "Nature's Blessing",
		
	["WK_ICW"] = "Improved Curse of Weakness",
	["WK_ShW"] = "Shadow Embrace",
	["WK_IHs"] = "Improved Healthstone",
	["WK_IIm"] = "Improved Imp",
	["WK_ISB"] = "Improved Shadow Bolt",
	
	["WR_MoS"] = "Mortal Strike",
	["WR_IDe"] = "Improved Demoralizing Shout",
	["WR_PiH"] = "Piercing Howl",
	["WR_IBa"] = "Improved Battle Shout",
	["WR_DeW"] = "Death Wish",
	["WR_LaS"] = "Last Stand",
	["WR_Def"] = "Defiance",
	["WR_IDi"] = "Improved Disarm",
	["WR_ISW"] = "Improved Shield Wall",
	["WR_IDS"] = "Improved Defensive Stance",
	["WR_Vit"] = "Vitality",
	
} end)